from typing import Protocol, Literal

from restaurant_task.domain.models.item.item import Item
from restaurant_task.domain.models.spot.spot_id import SpotId
from restaurant_task.domain.models.physical_item.physical_item import PhysicalItem

PoseName = Literal["default", "search", "serve", "grasp"]

class IRobotAgent(Protocol):
    async def detect_obstacle(self, max_distance: float) -> bool:...
    async def speak(self, sentence: str) -> None:...
    async def ask(self, question: str, duration_sec: int = 4) -> str:...
    async def move(self, x: float, y: float) -> None:...
    async def move_to(self, spot_id: SpotId) -> None:...
    async def rotate(self, r: float) -> None:...
    async def open_hand(self) -> None:...
    async def close_hand(self) -> None:...
    async def find_item(self, item: Item) -> PhysicalItem:...
    async def set_pose(self, pose_name: PoseName) -> None:...
    async def sleep(self, duration_sec: float) -> None:...
