from typing import Protocol, Literal

from restaurant_task.domain.models.item.item import Item
from restaurant_task.domain.models.spot.spot_id import SpotId
from restaurant_task.domain.models.physical_item.physical_item import PhysicalItem

PoseName = Literal["default", "search", "serve", "grasp"]

class IRobotAgent(Protocol):
    def detect_obstacle(self, max_distance: float) -> bool:...
    def speak(self, sentence: str) -> None:...
    def ask(self, question: str, duration_sec: int = 4) -> str:...
    def move(self, x: float, y: float) -> None:...
    def move_to(self, spot_id: SpotId) -> bool:...
    def open_hand(self) -> None:...
    def close_hand(self) -> None:...
    def find_item(self, item: Item) -> PhysicalItem:...
    def set_pose(self, pose_name: PoseName) -> None:...
